  name: Deploy to Google play

  on:
    push:
      branches: [main, prod]

  jobs:
    test:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4

        - name: Setup JDK 17
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: 17
            cache: 'gradle'

        - name: Grant execute permissions for gradlew
          run: chmod +x gradlew

    distribute:
      name: Distribute bundle to Google Play
      needs: test
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4

        - name: Setup JDK 17
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: 17
            cache: 'gradle'

        - name: Version Bump
          uses: chkfung/android-version-actions@v1.2.3



